title: Home Assistant Demo

sidebar:
  clock: digital
  date: true
  width: 25
  cards:
    - type: entity
      entity: light.bed_light
      name: "Bad"
      tap_action: 
        action: toggle
    - show_current: true
      show_forecast: false
      type: weather-forecast
      entity: weather.demo_weather_south
      forecast_type: daily

views:
  - type: sections
    title: Demo
    path: home
    icon: mdi:home-assistant
    sections:
      - title: Welcome 👋
        cards:
          - type: tile
            entity: light.bed_light
            name: Bed light
            tap_action: 
              action: toggle
  - type: sections
    title: LIving Room
    path: test
    icon: mdi:sofa
    sections:
      - title: Living room
        cards:
          - type: tile
            entity: light.bed_light
            name: Bed light
